export const GOOGLE_ADS_ID = "AW-653792266";
export const GOOGLE_ADS_CONVERSION_LABEL = "fPK1CKSKsuocEIqo4LcC";
export const GOOGLE_ADS_CONVERSION_SEND_TO =
  `${GOOGLE_ADS_ID}/${GOOGLE_ADS_CONVERSION_LABEL}`;

