import type { SeoProductPageConfig } from "@/components/seo/seo-product-page";

const related = {
  thumbnails: { href: "/generador-miniaturas-youtube", label: "Miniaturas para YouTube" },
  posts: { href: "/crear-posts-redes-sociales", label: "Posts para redes sociales" },
  banners: { href: "/generador-banners-portadas", label: "Banners y portadas" },
  recreate: { href: "/recreate-disenos", label: "Recreate" },
};

export const seoProductPages = {
  thumbnails: {
    slug: "generador-miniaturas-youtube",
    analyticsKey: "youtube_thumbnails",
    eyebrow: "Generador de miniaturas para YouTube",
    title: "Una miniatura que cuenta la historia antes del clic.",
    lead: "Convierte el título o la idea de tu video en una miniatura de YouTube con jerarquía clara, emoción contextual y texto pensado para leerse en el feed.",
    proofLabel: "Vista de miniatura",
    image: "/images/examples/gaming.webp",
    imageAlt: "Miniatura para YouTube de estilo gaming generada con Crealy",
    format: "1280 × 720",
    intent: "“Programé un juego en 24 horas sin saber programar.”",
    result: "Una escena con intriga, protagonista reconocible y una promesa visual fácil de entender.",
    benefits: [
      { title: "Texto que interpreta la idea", text: "Crealy identifica el giro más interesante del título y propone una frase breve, sin repetir fórmulas genéricas." },
      { title: "Composición para el feed", text: "Distribuye rostro, sujeto, texto y contraste pensando en cómo se verá la miniatura a tamaño reducido." },
      { title: "Personas reconocibles", text: "Puedes subir tus propias fotos para conservar identidad y añadir la expresión que pide la historia." },
    ],
    steps: [
      { title: "Describe el video", text: "Escribe el título, el reto o la historia. Cuanto más concreto sea el brief, mejor será la dirección." },
      { title: "Elige el enfoque", text: "Define estilo, texto visible, personas y elementos que deben aparecer." },
      { title: "Genera y descarga", text: "El trabajo entra en cola sin sacarte del flujo. Recibirás un aviso cuando esté listo." },
    ],
    faq: [
      { question: "¿Qué tamaño tienen las miniaturas?", answer: "Crealy entrega miniaturas en proporción 16:9 y exportación de 1280 × 720, preparada para YouTube." },
      { question: "¿Puedo usar mi propia foto?", answer: "Sí. Puedes subir personas y referencias visuales, identificarlas y explicar el papel que deben tener en la composición." },
      { question: "¿El texto puede ser automático?", answer: "Sí. Crealy resume la idea del video y elige una frase corta que refuerza curiosidad, urgencia o impacto según el contexto." },
    ],
    related: [related.posts, related.banners, related.recreate],
  },
  posts: {
    slug: "crear-posts-redes-sociales",
    analyticsKey: "social_posts",
    eyebrow: "Creador de posts para redes sociales",
    title: "Tu mensaje, diseñado para detener el scroll.",
    lead: "Crea posts para Instagram, Facebook, LinkedIn y X a partir de un brief sencillo. Crealy organiza el mensaje, el formato y la dirección visual sin convertir el proceso en un editor complejo.",
    proofLabel: "Post para redes",
    image: "/images/examples/productivity.webp",
    imageAlt: "Post profesional para redes sociales generado con Crealy",
    format: "1:1 · 4:5",
    intent: "“Anuncia mi nuevo servicio de consultoría con un tono profesional y cercano.”",
    result: "Una pieza legible, coherente con la plataforma y centrada en una sola acción.",
    benefits: [
      { title: "Copy visual automático", text: "Cuando eliges texto, Crealy redacta una frase precisa a partir de la información disponible y conserva nombres y marcas." },
      { title: "Formato desde el inicio", text: "Elige la red y la proporción antes de generar para mantener la jerarquía dentro del encuadre correcto." },
      { title: "Elementos con función", text: "Añade logos, productos, objetos o fondos con un identificador para que no aparezcan intercambiados ni al azar." },
    ],
    steps: [
      { title: "Cuenta qué quieres comunicar", text: "Indica oferta, anuncio, evento o idea y a quién va dirigido." },
      { title: "Define texto y referencias", text: "Decide si la pieza lleva texto, personas y elementos propios." },
      { title: "Recibe una pieza lista", text: "Crealy adapta composición y lectura al formato social elegido." },
    ],
    faq: [
      { question: "¿Qué redes sociales admite?", answer: "Puedes preparar piezas para Instagram, Facebook, LinkedIn y X con formatos compatibles con cada destino." },
      { question: "¿Tengo que escribir el texto exacto?", answer: "No. En posts, Crealy puede redactar automáticamente el texto visible desde tu brief, incluso cuando la información es breve." },
      { question: "¿Puedo añadir mi logo o producto?", answer: "Sí. Sube cada elemento, selecciona su tipo y escribe un identificador para que Crealy entienda qué representa." },
    ],
    related: [related.thumbnails, related.banners, related.recreate],
  },
  banners: {
    slug: "generador-banners-portadas",
    analyticsKey: "banners_covers",
    eyebrow: "Generador de banners y portadas",
    title: "Una portada diseñada para el espacio donde vivirá.",
    lead: "Genera banners de YouTube y portadas para Facebook, X y LinkedIn con medidas, proporciones y zonas seguras definidas antes de crear.",
    proofLabel: "Banner multicanal",
    image: "/images/hero/crealy-hero banner.webp",
    imageAlt: "Banner panorámico generado con Crealy",
    format: "Plataforma y medida real",
    intent: "“Una portada para mi canal de tecnología que se reconozca en móvil y televisión.”",
    result: "Un máster panorámico con el contenido importante dentro de la zona visible de cada dispositivo.",
    benefits: [
      { title: "Medidas por plataforma", text: "YouTube, Facebook, X y LinkedIn usan variantes propias. La interfaz muestra solo opciones compatibles." },
      { title: "Zonas seguras reales", text: "Texto, rostros y logos permanecen en áreas visibles frente a los distintos recortes de pantalla." },
      { title: "Banner de YouTube en alta calidad", text: "La portada de YouTube utiliza su flujo de máxima calidad y el tamaño panorámico definido para el producto." },
    ],
    steps: [
      { title: "Elige la plataforma", text: "Primero selecciona dónde publicarás para activar sus dimensiones y guías." },
      { title: "Describe la identidad", text: "Añade mensaje, estilo, personas, logos o elementos que deben conservarse." },
      { title: "Comprueba el recorte", text: "Revisa el resultado con las herramientas de zonas seguras antes de publicarlo." },
    ],
    faq: [
      { question: "¿El mismo banner sirve para todas las plataformas?", answer: "No siempre. Cada plataforma recorta y presenta las portadas de manera distinta; Crealy genera según el destino elegido." },
      { question: "¿Qué resolución usa el banner de YouTube?", answer: "El flujo de YouTube trabaja en alta calidad y prepara la portada en el tamaño panorámico indicado en la creación." },
      { question: "¿Puedo comprobar la zona segura?", answer: "Sí. Crealy incluye una herramienta pública para visualizar cómo se recorta un banner según el dispositivo." },
    ],
    related: [related.thumbnails, related.posts, related.recreate],
  },
  recreate: {
    slug: "recreate-disenos",
    analyticsKey: "recreate",
    eyebrow: "Recreate: recrear diseños",
    title: "Conserva la fórmula. Cambia la historia.",
    lead: "Sube una referencia que funciona y reconstruye su lógica visual con tu propio contenido. Crealy analiza composición, pose, iluminación, colores y tipografía sin copiar marcas ni personajes ajenos.",
    proofLabel: "Referencia → resultado",
    image: "/images/examples/fitness.webp",
    imageAlt: "Ejemplo de un diseño reinterpretado con Recreate de Crealy",
    format: "Hasta 4 elementos",
    intent: "Una referencia con buena jerarquía, tensión visual y distribución efectiva.",
    result: "Una pieza original que mantiene la lógica elegida e integra tus sujetos y elementos identificados.",
    benefits: [
      { title: "Análisis antes de generar", text: "Recreate convierte la referencia en decisiones editables: composición, pose, luz, color y tratamiento tipográfico." },
      { title: "Identidad protegida", text: "Las caras subidas se tratan como identidades distintas y se evalúan para detectar omisiones o duplicados." },
      { title: "Elementos bien asignados", text: "Puedes identificar personas, logos, productos, objetos y fondos para indicar qué papel cumple cada imagen." },
    ],
    steps: [
      { title: "Sube la referencia principal", text: "Utiliza una pieza propia o una referencia permitida cuya estructura quieras reinterpretar." },
      { title: "Ajusta qué conservar", text: "Revisa el análisis y decide cuánto mantener de composición, pose, iluminación, colores y tipografía." },
      { title: "Añade tu contenido", text: "Sube hasta cuatro elementos según tu plan, identifica cada uno y describe el resultado que buscas." },
    ],
    faq: [
      { question: "¿Recreate copia exactamente el diseño?", answer: "No. Extrae su lógica visual para producir una pieza original con tu contenido y evita replicar marcas, texto o personajes protegidos de la referencia." },
      { question: "¿Cuántas referencias adicionales puedo usar?", answer: "Puedes añadir hasta cuatro elementos según tu plan. Cada archivo puede identificarse como persona, logo, producto, objeto o fondo." },
      { question: "¿Puedo conservar la cara de una persona?", answer: "Sí. Las fotos subidas reciben instrucciones estrictas de identidad y controles para detectar sujetos omitidos, duplicados o alterados." },
    ],
    related: [related.thumbnails, related.posts, related.banners],
  },
} as const satisfies Record<string, SeoProductPageConfig>;
