"use client";

import { ArrowRight, Check, Copy, Crown, ImagePlus, MoreHorizontal, Plus, Sparkles, Trash2, Upload, X } from "lucide-react";
import Image from "next/image";
import Link from "next/link";
import { useRef, useState } from "react";

import type { BrandStyleEntitlement } from "@/config/brand-styles";
import { trackConversion } from "@/lib/analytics/events";
import { cn } from "@/lib/utils";
import { uploadPrivateImage } from "@/lib/uploads/upload-private-image";
import type { BrandStyle } from "@/types/brand-style";
import type { PlanKey } from "@/types/billing";

type Props = { initialStyles: BrandStyle[]; plan: PlanKey; entitlement: BrandStyleEntitlement };
type Notice = { tone: "success" | "error"; text: string } | null;

async function json<T>(response: Response): Promise<T> { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error((data as { error?: string }).error || "No pudimos completar la acción."); return data as T; }

export function BrandStyleStudio({ initialStyles, plan, entitlement }: Props) {
  const [styles, setStyles] = useState(initialStyles);
  const [creating, setCreating] = useState(false);
  const [draft, setDraft] = useState<BrandStyle | null>(null);
  const [name, setName] = useState("");
  const [busy, setBusy] = useState<"create" | "upload" | "analyze" | null>(null);
  const [notice, setNotice] = useState<Notice>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const atLimit = styles.length >= entitlement.maxStyles;

  function start() {
    if (!entitlement.enabled) { trackConversion("brand_style_upgrade_clicked", { plan }); return; }
    if (atLimit) { trackConversion("brand_style_limit_reached", { plan }); setNotice({ tone: "error", text: entitlement.maxStyles === 1 ? "El plan Creator permite guardar un estilo visual. Mejora a Pro para gestionar varias marcas o canales." : "Has alcanzado el límite de estilos de tu plan." }); return; }
    setCreating(true); setDraft(null); setName(""); setNotice(null); trackConversion("brand_style_creation_started", { plan });
  }

  async function createDraft() {
    if (!name.trim()) return setNotice({ tone: "error", text: "Escribe un nombre para tu firma visual." });
    setBusy("create"); try { const result = await json<{ style: BrandStyle }>(await fetch("/api/brand-styles", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) })); setDraft(result.style); setStyles((current) => [result.style, ...current]); setNotice(null); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "No pudimos crear la firma visual." }); } finally { setBusy(null); }
  }

  async function upload(files: File[]) {
    if (!draft || !files.length) return; const remaining = entitlement.maxReferences - draft.referenceImages.length; const selected = files.slice(0, remaining); if (!selected.length) return;
    setBusy("upload");
    try { const uploadIds: string[] = []; for (const file of selected) uploadIds.push((await uploadPrivateImage(file, "reference")).uploadId); const result = await json<{ style: BrandStyle }>(await fetch(`/api/brand-styles/${draft.id}/references`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ uploadIds }) })); setDraft(result.style); setStyles((current) => current.map((item) => item.id === result.style.id ? result.style : item)); trackConversion("brand_style_references_uploaded", { plan, reference_count: result.style.referenceImages.length }); setNotice({ tone: "success", text: `${result.style.referenceImages.length} referencias listas para analizar.` }); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "No pudimos subir las referencias." }); } finally { setBusy(null); }
  }

  async function removeReference(referenceId: string) {
    if (!draft) return; const response = await fetch(`/api/brand-styles/${draft.id}/references/${referenceId}`, { method: "DELETE" }); if (!response.ok) return setNotice({ tone: "error", text: "No pudimos eliminar la referencia." }); const next = { ...draft, referenceImages: draft.referenceImages.filter((item) => item.id !== referenceId), analysisStatus: "pending" as const }; setDraft(next); setStyles((current) => current.map((item) => item.id === next.id ? next : item));
  }

  async function analyze() {
    if (!draft || draft.referenceImages.length < entitlement.minReferences) return setNotice({ tone: "error", text: `Añade al menos ${entitlement.minReferences} referencias similares.` });
    setBusy("analyze"); const started = Date.now(); try { const { analysis } = await json<{ analysis: { summary: string; attributes: BrandStyle["visualAttributes"]; consistencyScore: number; warnings: string[] } }>(await fetch(`/api/brand-styles/${draft.id}/analyze`, { method: "POST" })); const next = { ...draft, visualSummary: analysis.summary, description: analysis.summary, visualAttributes: analysis.attributes, consistencyScore: analysis.consistencyScore, warnings: analysis.warnings, analysisStatus: "ready" as const }; setDraft(next); setStyles((current) => current.map((item) => item.id === next.id ? next : item)); trackConversion("brand_style_analysis_completed", { plan, reference_count: next.referenceImages.length, duration_bucket: Date.now() - started < 15000 ? "fast" : "standard" }); setNotice({ tone: "success", text: "Crealy ha detectado tu identidad visual." }); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "No pudimos analizar tus referencias." }); } finally { setBusy(null); }
  }

  async function rename() {
    if (!draft || !name.trim() || name.trim() === draft.name) return;
    try {
      const result = await json<{ style: BrandStyle }>(await fetch(`/api/brand-styles/${draft.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name }) }));
      setDraft(result.style); setStyles((current) => current.map((item) => item.id === result.style.id ? result.style : item)); setNotice({ tone: "success", text: "Nombre actualizado." });
    } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "No pudimos actualizar el nombre." }); }
  }

  async function deleteStyle(style: BrandStyle) {
    if (!confirm("¿Eliminar este estilo? Las referencias y la configuración se eliminarán permanentemente. Tus diseños ya generados no se verán afectados.")) return;
    const response = await fetch(`/api/brand-styles/${style.id}`, { method: "DELETE" }); if (!response.ok) return setNotice({ tone: "error", text: "No pudimos eliminar el estilo." }); setStyles((current) => current.filter((item) => item.id !== style.id)); if (draft?.id === style.id) { setDraft(null); setCreating(false); } trackConversion("brand_style_deleted", { plan }); setNotice({ tone: "success", text: "Estilo eliminado." });
  }

  async function duplicate(style: BrandStyle) {
    try { await json(await fetch(`/api/brand-styles/${style.id}/duplicate`, { method: "POST" })); location.reload(); } catch (error) { setNotice({ tone: "error", text: error instanceof Error ? error.message : "No pudimos duplicar el estilo." }); }
  }

  if (!entitlement.enabled) return <PremiumState plan={plan} />;

  return <div className="mx-auto max-w-6xl">
    <header className="flex flex-col gap-6 border-b border-white/10 pb-8 sm:flex-row sm:items-end sm:justify-between">
      <div><h1 className="text-4xl font-semibold tracking-[-0.035em] text-foreground sm:text-5xl">Tu firma, en cada creación</h1><p className="mt-3 max-w-2xl text-base leading-7 text-muted">Convierte tus mejores diseños en una identidad visual reutilizable. Crealy aprende los patrones; cada nueva pieza sigue siendo original.</p></div>
      <button onClick={start} disabled={atLimit} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-brand px-5 text-sm font-bold text-brand-ink transition-transform hover:-translate-y-0.5 disabled:cursor-not-allowed disabled:opacity-45"><Plus className="size-4" /> Crear firma visual</button>
    </header>
    {notice ? <div role="status" className={cn("mt-5 rounded-xl border px-4 py-3 text-sm", notice.tone === "success" ? "border-brand/25 bg-brand/[0.06] text-foreground" : "border-red-400/25 bg-red-400/[0.06] text-red-100")}>{notice.text}</div> : null}
    {creating ? <section className="mt-8 grid gap-8 lg:grid-cols-[minmax(0,1fr)_18rem]">
      <div className="rounded-2xl border border-white/10 bg-surface p-5 sm:p-7">
        {!draft ? <div><h2 className="text-2xl font-semibold text-foreground">Ponle nombre a tu identidad</h2><p className="mt-2 text-sm leading-6 text-muted">Usa un nombre que puedas reconocer al crear.</p><label className="mt-7 block text-sm font-semibold text-foreground">Nombre de la firma<input autoFocus maxLength={80} value={name} onChange={(event) => setName(event.target.value)} placeholder="Ej. Firma principal del canal" className="mt-2 h-12 w-full rounded-xl border border-white/12 bg-background px-4 text-foreground outline-none transition-colors placeholder:text-white/35 focus:border-brand/65" /></label><button onClick={createDraft} disabled={busy === "create"} className="mt-5 inline-flex h-11 items-center gap-2 rounded-xl bg-brand px-5 text-sm font-bold text-brand-ink disabled:opacity-50">{busy === "create" ? "Guardando…" : "Continuar"}<ArrowRight className="size-4" /></button></div> :
        <div><div className="flex items-start justify-between gap-4"><div className="min-w-0 flex-1"><h2 className="text-2xl font-semibold text-foreground">Añade tus mejores referencias</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">Elige diseños que compartan la misma identidad. Cuanto más coherentes sean, mejores serán los resultados.</p><div className="mt-5 flex max-w-lg gap-2"><label className="sr-only" htmlFor="activeStyleName">Nombre del estilo</label><input id="activeStyleName" value={name} maxLength={80} onChange={(event) => setName(event.target.value)} className="h-10 min-w-0 flex-1 rounded-lg border border-white/10 bg-background px-3 text-sm text-foreground outline-none focus:border-brand/60"/><button type="button" onClick={() => void rename()} className="h-10 rounded-lg border border-white/12 px-3 text-xs font-semibold text-foreground hover:bg-white/5">Guardar nombre</button></div></div><button aria-label="Cerrar" onClick={() => { setCreating(false); setDraft(null); }} className="rounded-lg p-2 text-muted hover:bg-white/5 hover:text-foreground"><X className="size-5" /></button></div>
          <button onClick={() => inputRef.current?.click()} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); void upload(Array.from(event.dataTransfer.files)); }} disabled={busy === "upload" || draft.referenceImages.length >= entitlement.maxReferences} className="mt-6 flex min-h-44 w-full flex-col items-center justify-center rounded-2xl border border-dashed border-white/20 bg-background p-6 text-center transition-colors hover:border-brand/50 disabled:opacity-50"><Upload className="size-6 text-brand" /><span className="mt-3 font-semibold text-foreground">{busy === "upload" ? "Optimizando y subiendo…" : "Arrastra tus miniaturas aquí"}</span><span className="mt-1 text-xs text-muted">JPG, PNG o WebP · máximo 8 MB · {entitlement.minReferences}–{entitlement.maxReferences} referencias</span></button>
          <input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" multiple hidden onChange={(event) => { void upload(Array.from(event.target.files ?? [])); event.target.value = ""; }} />
          <div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{draft.referenceImages.map((reference, index) => <div key={reference.id} className="group relative aspect-video overflow-hidden rounded-xl bg-background">{reference.imageUrl ? <Image src={reference.imageUrl} alt={`Referencia ${index + 1}`} fill unoptimized className="object-cover" /> : null}<button onClick={() => void removeReference(reference.id)} aria-label={`Eliminar referencia ${index + 1}`} className="absolute right-2 top-2 rounded-lg bg-black/75 p-2 text-white opacity-100 transition-opacity sm:opacity-0 sm:group-hover:opacity-100"><Trash2 className="size-4" /></button></div>)}</div>
          <div className="mt-6 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-5"><p className="text-sm text-muted"><strong className="text-foreground">{draft.referenceImages.length}</strong> de {entitlement.maxReferences} referencias</p><button onClick={analyze} disabled={busy === "analyze" || draft.referenceImages.length < entitlement.minReferences} className="inline-flex h-11 items-center gap-2 rounded-xl bg-brand px-5 text-sm font-bold text-brand-ink disabled:opacity-45"><Sparkles className="size-4" />{busy === "analyze" ? "Analizando patrones…" : draft.analysisStatus === "ready" ? "Analizar de nuevo" : "Analizar mi firma"}</button></div>
          {draft.visualSummary ? <Analysis style={draft} onConfirm={() => { setCreating(false); setDraft(null); trackConversion("brand_style_created", { plan, reference_count: draft.referenceImages.length }); setNotice({ tone: "success", text: "Tu firma visual está lista para usar." }); }} /> : null}
        </div>}
      </div>
      <aside className="space-y-3"><Progress active={!draft ? 1 : draft.visualSummary ? 3 : 2} /><p className="rounded-xl border border-white/10 bg-white/[0.025] p-4 text-xs leading-5 text-muted">Tu firma influye en la estética, no copia personas, objetos, textos ni composiciones de las referencias.</p></aside>
    </section> : null}
    {!creating && styles.length === 0 ? <EmptyState onCreate={start} /> : null}
    {!creating && styles.length > 0 ? <section className="mt-8"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-semibold text-foreground">Tus estilos</h2><span className="text-sm text-muted">{styles.length} de {entitlement.maxStyles}</span></div><div className="grid gap-4 md:grid-cols-2">{styles.map((style) => <StyleCard key={style.id} style={style} canDuplicate={entitlement.canDuplicate} onEdit={() => { setDraft(style); setName(style.name); setCreating(true); }} onDuplicate={() => void duplicate(style)} onDelete={() => void deleteStyle(style)} />)}</div></section> : null}
  </div>;
}

function PremiumState({ plan }: { plan: PlanKey }) { return <div className="relative mx-auto grid min-h-[36rem] max-w-5xl place-items-center overflow-hidden rounded-3xl border border-brand/20 bg-surface px-6 py-16 text-center"><div aria-hidden="true" className="absolute left-1/2 top-0 h-px w-2/3 -translate-x-1/2 bg-brand"/><div className="relative max-w-xl"><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-brand text-brand-ink shadow-[0_14px_44px_rgba(221,245,39,0.12)]"><Crown className="size-7" /></div><div className="mt-6 inline-flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.12em] text-brand"><Crown aria-hidden="true" className="size-3.5" /> Exclusivo Creator · Pro</div><h1 className="mt-4 text-4xl font-semibold tracking-[-0.035em] text-foreground sm:text-5xl">Haz que reconozcan tu firma</h1><p className="mt-4 text-base leading-7 text-muted">Crealy aprende los patrones visuales de tu marca y los mantiene presentes en nuevas creaciones originales.</p><Link href="/pricing" onClick={() => trackConversion("brand_style_upgrade_clicked", { plan })} className="mt-7 inline-flex h-12 items-center gap-2 rounded-xl bg-brand px-6 text-sm font-bold text-brand-ink transition-transform hover:-translate-y-0.5">Desbloquear Firma visual <ArrowRight className="size-4" /></Link></div></div>; }
function EmptyState({ onCreate }: { onCreate: () => void }) { return <div className="mt-8 grid min-h-[28rem] place-items-center rounded-3xl border border-white/10 bg-surface px-6 py-14 text-center"><div className="max-w-lg"><div className="relative mx-auto h-36 w-64"><div className="absolute left-0 top-5 aspect-video w-32 -rotate-6 rounded-xl border border-white/10 bg-background"/><div className="absolute right-0 top-5 aspect-video w-32 rotate-6 rounded-xl border border-white/10 bg-background"/><div className="absolute left-1/2 top-10 aspect-video w-36 -translate-x-1/2 rounded-xl border border-brand/45 bg-brand/[0.09] shadow-[0_18px_50px_rgba(221,245,39,.08)]"><Sparkles className="absolute left-1/2 top-1/2 size-6 -translate-x-1/2 -translate-y-1/2 text-brand" /></div></div><h2 className="text-2xl font-semibold text-foreground">Tu marca, reconocible en cada creación</h2><p className="mt-3 text-sm leading-6 text-muted">Sube algunas miniaturas que representen tu marca. Crealy aprenderá sus patrones visuales para mantener una identidad consistente.</p><button onClick={onCreate} className="mt-6 inline-flex h-11 items-center gap-2 rounded-xl bg-brand px-5 text-sm font-bold text-brand-ink"><ImagePlus className="size-4" /> Crear firma visual</button></div></div>; }
function Progress({ active }: { active: number }) { return <ol className="rounded-xl border border-white/10 bg-surface p-4">{["Nombre", "Referencias", "Confirmación"].map((label, index) => <li key={label} className="flex items-center gap-3 py-2"><span className={cn("grid size-7 place-items-center rounded-full text-xs font-bold", index + 1 < active ? "bg-brand text-brand-ink" : index + 1 === active ? "border border-brand text-brand" : "border border-white/15 text-muted")}>{index + 1 < active ? <Check className="size-4" /> : index + 1}</span><span className={cn("text-sm", index + 1 === active ? "font-semibold text-foreground" : "text-muted")}>{label}</span></li>)}</ol>; }
function Analysis({ style, onConfirm }: { style: BrandStyle; onConfirm: () => void }) { const values = style.visualAttributes ? Object.values(style.visualAttributes).flat().slice(0, 8) : []; return <div className="mt-7 rounded-2xl border border-brand/20 bg-brand/[0.045] p-5"><div className="flex items-center gap-2 text-sm font-semibold text-brand"><Check className="size-4" /> Crealy ha detectado</div><p className="mt-3 text-base leading-7 text-foreground">{style.visualSummary}</p><div className="mt-4 flex flex-wrap gap-2">{values.map((value) => <span key={value} className="rounded-lg bg-black/30 px-2.5 py-1.5 text-xs text-white/75">{value}</span>)}</div>{style.warnings.length || (style.consistencyScore ?? 100) < 55 ? <div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[0.05] p-4"><p className="font-semibold text-amber-100">Tus referencias utilizan estilos diferentes</p><p className="mt-1 text-sm leading-6 text-amber-50/70">Para resultados más consistentes, selecciona piezas de una misma identidad. Puedes continuar de todos modos.</p></div> : null}<button onClick={onConfirm} className="mt-5 inline-flex h-11 items-center gap-2 rounded-xl bg-brand px-5 text-sm font-bold text-brand-ink"><Check className="size-4" /> Esta es mi firma</button></div>; }
function StyleCard({ style, canDuplicate, onEdit, onDuplicate, onDelete }: { style: BrandStyle; canDuplicate: boolean; onEdit: () => void; onDuplicate: () => void; onDelete: () => void }) { return <article className="overflow-hidden rounded-2xl border border-white/10 bg-surface"><div className="grid aspect-[2.4/1] grid-cols-3 gap-px bg-white/10">{style.referenceImages.slice(0,3).map((ref, index) => <div key={ref.id} className="relative bg-background">{ref.imageUrl ? <Image src={ref.imageUrl} alt={`Referencia de ${style.name} ${index + 1}`} fill unoptimized className="object-cover" /> : null}</div>)}</div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-foreground">{style.name}</h3><p className="mt-1 text-xs text-muted">{style.referenceImages.length} referencias · actualizado {new Intl.DateTimeFormat("es", { day: "numeric", month: "short" }).format(new Date(style.updatedAt))}</p></div><MoreHorizontal className="size-5 text-muted" /></div><p className="mt-4 line-clamp-2 min-h-10 text-sm leading-5 text-muted">{style.visualSummary || "Completa el análisis para empezar a usar esta identidad."}</p><div className="mt-4 flex flex-wrap gap-2">{style.supportedDesignTypes.map((type) => <span key={type} className="rounded-md bg-white/[0.05] px-2 py-1 text-xs text-white/65">{type === "thumbnail" ? "Miniaturas" : type === "social-post" ? "Posts" : type === "social-cover" ? "Covers" : "Banners"}</span>)}</div><div className="mt-5 flex flex-wrap gap-2"><Link href={`/create?type=${style.supportedDesignTypes[0]}&style=${style.id}`} className="inline-flex h-10 flex-1 items-center justify-center gap-2 rounded-xl bg-brand px-4 text-sm font-bold text-brand-ink">Usar estilo <ArrowRight className="size-4" /></Link><button onClick={onEdit} className="h-10 rounded-xl border border-white/12 px-4 text-sm font-semibold text-foreground hover:bg-white/5">Editar</button>{canDuplicate ? <button onClick={onDuplicate} aria-label="Duplicar estilo" className="grid size-10 place-items-center rounded-xl border border-white/12 text-muted hover:text-foreground"><Copy className="size-4" /></button> : null}<button onClick={onDelete} aria-label="Eliminar estilo" className="grid size-10 place-items-center rounded-xl border border-white/12 text-muted hover:border-red-400/30 hover:text-red-300"><Trash2 className="size-4" /></button></div></div></article>; }
